name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.11
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0
  flutter_rating_bar: ^4.0.1



  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/assignment1/
    - assets/assignment2/
    - assets/assignment3/
    - assets/assignment4/
    - assets/assignment6/
    - assets/assignment7/
    - assets/assignment8/
    - assets/assignment9/
    - assets/assignment11/germany/
    - assets/assignment11/italy/
    - assets/assignment11/spain/
    - assets/assignment11/india/
    - assets/assignment11/uae/
    - assets/assignment12/
    - assets/assignment13/
    - assets/assignment14/
  fonts:
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-BoldItalic.ttf
        - asset: assets/fonts/Amaranth-Italic.ttf
